spring:
  application:
    name: recipeManager
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipes?serverTimezone=US/Eastern&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: cccc1998
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


